version: 2
updates:
  # dev dependencies: new Kimai releases arrive here, CI then checks the plugin against them
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "develop"

  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "monthly"
    target-branch: "develop"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "develop"
